name: Newone
favicon: null
layout_spectrum: 0.9649048903957009
typography_spectrum: 0.8190467667300254
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6969749657437205
  lightness: 0.7866618323605508
  saturation: 0.6792153615970165
  rhythmicContrast: 0.5054820834193379
purpose: []
